### ISSUE TITLE
Ionic app gives CordovaHttpPlugin should use a background thread in iOS 10.2 emulator

### ISSUE THREAD

**Issue by HobieCat** [wymsee/cordova-HTTP#131]
Hello there,

I'm using the plugin in one of my ionic projects and was addressed here by the last comment found [here](https://issues.apache.org/jira/browse/CB-2415) in order to manage a 401 error code sent back by a call to a REST API.

I am doing some tests now and am able to inject the plugin object in my angular factory but when I try to call a get method using this code:
```javascript
cordovaHTTP.get("https://jsonplaceholder.typicode.com/posts/1",{},{},
      function(response) {
          console.log("cordovaHTTP SUCCESS");
          console.log(response.status);
      }, function(response) {
          console.log("cordovaHTTP ERROR");
          console.log(response.error);
      });
```

All that I have logged in the console when run on the iOS 10.2 Simulator is:
```
***** cordovaHTTP *****
THREAD WARNING: ['CordovaHttpPlugin'] took '356.676025' ms. Plugin should use a background thread.
***** END cordovaHTTP *****
```

Has anyone of you ever faced a similar issue? Can you please give me some directions towards possible solutions?

My ionic development is:
```
> ionic info

Your system information:

Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

Many thanks and greetings!

**Comment by duddu** [comment]
Hi @HobieCat, 
Cordova plugins by default run on the UI thread, so with that warning cordova is simply telling that you should execute every plugin methods on a background thread in order not to block the main one ([see here](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/plugin.html#threading)).
This plugin executes tasks in background on Android only, therefore on iOS you will get that warning logged on each callback. Although it's against the guidelines, it's not an error itself and won't prejudice any functionality on your app.

**Comment by HobieCat** [comment]
Hello @duddu, thank you for your reply.
Yes, I'm aware of the warnings thrown on a non background thread.
Still, my callbacks are never ever run.
I use the console.log call to output into the simulator's console through the Safari browser, where nothing gets logged and no XHR resource shows up in the Network panel of the inspector.
On the other hand, I guess that the cordovaHTTP object gets correctly injected into my angular factory because if I add a `console.log(cordovaHTTP)` the object is logged to the console and there's no error.

**Comment by HobieCat** [comment]
Further investigations showed that if I change the code to:
```javascript
cordovaHTTP.get("https://jsonplaceholder.typicode.com/posts/1",{},{}).
    then(
      function(response) {
          console.log("cordovaHTTP SUCCESS");
          console.log(response.status);
      }, function(response) {
          console.log("cordovaHTTP ERROR");
          console.log(response.error);
      });
```
everything is working as expected.
Could be because of the angular environment I'm in?
Maybe it's worth a documentation fix?

**Comment by duddu** [comment]
Sorry, I got it wrong before, and didn't see the error in the code.
Yes, if you call the plugin methods from the injected angular service `cordovaHTTP`, any method returns a Promise object, which you have to resolve in order to get your response/error body, like you showed in the last comment.
In the Usage > AngularJS section of the README you can find the reference to Angular promises usage.

**Comment by HobieCat** [comment]
Great! So this is not an issue anymore, closing with many thanks.

**Comment by socionerd** [comment]
Hi @HobieCat,

How did you import the CordovaHTTP into ionic 2? Always returns the error that CordovaHTTP is not declared.

I added the plugin with "cordova plugin add cordova-plugin-http" but I can not call cordovaHTTP.anymethod. I tried to import in several ways but I could not.

I saw that you got it working on Ionic 2. Can you help me?

**Comment by HobieCat** [comment]
Hello,
please note that my application is not an Ionic v2 app, but a v1 instead.

Basically, [this](https://github.com/wymsee/cordova-HTTP/issues/126?_pjax=%23js-repo-pjax-container#issuecomment-280950434) comment by gregswindle did the trick, give it a try on Ionic 2.

**Comment by alexszilagyi** [comment]
@HobieCat: Could you please share how you've managed to integrate the cordovaHTTP plugin ?

**Comment by HobieCat** [comment]
Hello @alexszilagyi,
the source code is a private project for one of my company's customers and cannot be shared.
Moreover, it's almost 3 months that I'm not active anymore on that so I could try to share what I recall of the logic I've been using and just a few lines of code.

First of all you need `cordova-plugin-http` in the `cordovaPlugins` section of the `package.json`, then you need the `oclazyload` in the` bower.json`. These are the dependencies you need to have installed.

Now some code.

1. include oclazyload in your index.html 
```html
 <script src="lib/oclazyload/dist/ocLazyLoad.min.js"></script>
```
2. Then, define a factory (let's call it cordovaHttpInjector) following the already mentioned comment by gregswindle

1. Lastly use that factory wherever you need, more or less like:
```javascript
cordovaHttpInjector.inject().then(
   function (cordovaHTTP) {
   cordovaHTTP.get("https://jsonplaceholder.typicode.com/posts/1",{},{}).
       then(
         function(response) {
             console.log("cordovaHTTP SUCCESS");
             console.log(response.status);
         }, function(response) {
             console.log("cordovaHTTP ERROR");
             console.log(response.error);
         });
   },
   function (reason) {
       throw new Error(reason);
   }
);
```
Remember to first inject the cordovaHttpInjector wherever you're using it and that I'm referring to an Angular 1.x application (that is what the ocLazyLoad it's for by the way).

I cannot give a copy and paste answer, this is all I can share but I think you've got all the ingredients to get it cooked!

**Comment by alex17pat** [comment]
One of the Best iOS Emulators which  I know are

1. Ipadian
2. SmartFace
3. Appetize.Io
4. AIR Iphone
5. Xamarin Testflight

source:-[ http://merabheja.com/ios-emulators-for-windows/]( http://merabheja.com/ios-emulators-for-windows/)
