### ISSUE TITLE
Update to Depend on Latest Cordova File Plugin

### ISSUE THREAD

**Issue by TheKiteEatingTree** [wymsee/cordova-HTTP#19]
We're currently dependent on version 0.2.5 and we resisted updating because of bugs in 1.0.0.  Cordova is now on 1.3.1 so we should reevaluate and try to update.

**Comment by denisbabineau** [comment]
@TheKiteEatingTree can you point to specific issues encountered/bugs that prevented you from updated? We're using v2.0.0 of cordova-plugin-file so I'll be looking at updating the dependencies. Thanks.

**Comment by TheKiteEatingTree** [comment]
There was some bug in 1.0.0 that we considered critical.  I'm sure that's fixed and I don't even remember what it was.  IIRC the other issues with updating the file plugin weren't directly related to cordova-http, but rather other parts of our specific app.  I don't think I ever specifically looked into updating cordova-http.
