### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by norgen** [wymsee/cordova-HTTP#41]
Build in osx for ios platform error:

Undefined symbols for architecture i386:
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[AFNetworkReachabilityManager managerForAddress:] in AFNetworkReachabilityManager.o
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[AFNetworkReachabilityManager managerForDomain:] in AFNetworkReachabilityManager.o
  "_SCNetworkReachabilityGetFlags", referenced from:
      ___47-[AFNetworkReachabilityManager startMonitoring]_block_invoke54 in AFNetworkReachabilityManager.o
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[AFNetworkReachabilityManager startMonitoring] in AFNetworkReachabilityManager.o
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[AFNetworkReachabilityManager startMonitoring] in AFNetworkReachabilityManager.o
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[AFNetworkReachabilityManager stopMonitoring] in AFNetworkReachabilityManager.o
ld: symbol(s) not found for architecture i386

**Comment by lovery** [comment]
Hi norgen,

I received the same error several times and the only thing sole the problem is to remove all plugins and iOS platform and add plugins and platform again.

If you want I could search for the resource which helped me to solve the problem.
