### ISSUE TITLE
Need help: cordovaHTTP stops JS processing

### ISSUE THREAD

**Issue by Fmstrat** [wymsee/cordova-HTTP#45]
Hi wymsee,

This may just be misuse, but I've followed the instructions and created a simple little app that represents a crash I'm having. Here's the code:

	var app = {
			initialize: function() {
					this.bindEvents();
			},
			bindEvents: function() {
					document.addEventListener('deviceready', this.onDeviceReady, false);
			},
			onDeviceReady: function() {
					init();
			},
	};

	function init() {
		acceptAllCerts(true);
	}

	function acceptAllCerts(b) {
				console.log('acceptAllCerts');
				cordovaHTTP.acceptAllCerts(b, function() {
						console.log('success');
				}, function() {
						console.log('fail');
				});
	}

The code prints out "acceptAllCerts" but never gets to the failure or success. All JS processing just stops with no errors reported. I've tried installing both with:

    cordova plugin add https://github.com/wymsee/cordova-HTTP.git

and with

    cordova plugin add com.synconset.cordovahttp 

... since they were both in the instructions on http://plugins.cordova.io/#/package/com.synconset.cordovahttp, but neither works for me. Any idea what I'm doing wrong?

This is codrova > 3 and running on Android for now, but will run on iOS in the future. Thanks.

**Comment by Fmstrat** [comment]
I've narrowed it down to if I move the cordovaHTTP access into the "app" object, it works. But that doesn't suit how my app is built. How would I access the cordovaHTTP object from outside app? Thanks.

**Comment by jaarandaz** [comment]
@Fmstrat can you put an example of acceptAllCerts working? I Cannot figure it out

**Comment by TheKiteEatingTree** [comment]
This seems like the acceptAllCerts never calls the callback bug that was fixed via a PR.  Reopen if that's not the case
