### ISSUE TITLE
Potential iOS Security Issue: AFNetworking Library

### ISSUE THREAD

**Issue by Fmstrat** [wymsee/cordova-HTTP#47]
Hi,

It appears that the AFNetworking library used by cordova-HTTP has a major security flaw leading to the interception of HTTPS data on iOS. Here is the run-down:

http://www.macrumors.com/2015/04/21/security-flaws-1500-ios-apps-rootpipe/

The fix is in the latest AFNetworking release:

https://github.com/AFNetworking/AFNetworking/releases/tag/2.5.3

It is unlikely that 2.4.1 AFNetworking used in cordova-HTTP is at risk, but I'm not sure they've evaluated anything prior to 2.5. Therefore I'd recommend confirming 2.4.1 does not have the issue and notating the code to ensure future updates never use anything lower than 2.5.3, or go ahead and update the library to 2.5.3 to be safe.

**Comment by CSullivan102** [comment]
Thanks for the heads up, from reading around, especially the below blog post/quote, it looks like the vulnerability was specifically introduced in 2.5.1, so this plugin should be fine right now. We'll look into updating to 2.5.3 when we have a little time.

https://sourcedna.com/blog/20150420/afnetworking-vulnerability.html

> First, we had to determine the vulnerability window. We found the AFNetworking flaw was present in the Github repo from January 24 through March 25. More importantly, it had been released as version 2.5.1 on February 12 before being fixed in version 2.5.2. Any developer who updated their app during that window could have integrated the vulnerable library.

**Comment by Fmstrat** [comment]
Great, thanks! It looks like I may have identified another with a TLSv1/SSLv3 requirement, too. I'll post as a separate issue in case you don't get notified of comments on closed issues.
