### ISSUE TITLE
TLSv1 or SSLv3 required: Potential security issue?

### ISSUE THREAD

**Issue by Fmstrat** [wymsee/cordova-HTTP#48]
It seems that in cordova-HTTP's current configuration, TLSv1 or SSLv3 are required. A standard apache configuration to keep things secure since the POODLE bug has been:

    SSLProtocol +TLSv1.2 +TLSv1.1 -TLSv1 -SSLv3 -SSLv2
    SSLCipherSuite 'ECDH+AESGCM:DH+AESGCM:ECDH+AES:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS:!3DES'
    SSLHonorCipherOrder On

However, without `+TLSv1` or `+SSLv3` cordova-HTTP fails to connect. This means that to use a cordova-HTTP app, the server has to be setup to allow potentially vulnerable clients.

As a note, I'm working on an application that integrates with ownCloud, so many of their user's servers are enterprise ready and require the above security settings (I.E. they cannot be changed).

Is this something that can be corrected in the way cordova-HTTP is configured within the app?

Thanks in advance.

**Comment by Fmstrat** [comment]
In digging deeper, I found this in https://github.com/wymsee/cordova-HTTP/blob/f9fc028546931967f3d6f2fd09ada9893bcb0b14/src/android/com/synconset/CordovaHTTP/HttpRequest.java:

    SSLContext context = SSLContext.getInstance("TLS");

Could this be the culprit since it's not the default? I believe forcing TLS sets TLSv1 and SSLv3, but does not include TLSv1.1 or TLSv1.2.

**Comment by Fmstrat** [comment]
It seems after further investigation, this bug may need to be pushed all the way up to the http-request library unless you have ideas I don't. Based on the following:

https://androidfarming.wordpress.com/2015/03/28/android-tlsv1-2-and-ssl-pinning/
http://stackoverflow.com/questions/16531807/android-client-server-on-tls-v1-2

It looks like a custom socket object is required to allow for higher security standards. If you don't think this is possible to correct in cordova-HTTP, let me know and I'll reference this issue at https://github.com/kevinsawicki/http-request

**Comment by Fmstrat** [comment]
As you can see I've created a bug and pull-request with http-request. I will do the same for you in a few moments.

**Comment by brendonparker** [comment]
I started getting the error "SSL handshake failed". Could that be related to this? I swear this was working last week, and just stopped working. Based on what I can tell all my root certs on the device are good. Not sure if something changed on the server side?

**Comment by brendonparker** [comment]
Never mind... just figured it out. The datetime on the device was off, which was breaking the ssl.

**Comment by allie-wake-up** [comment]
Should be taken care of by #95.  I also want to note that this issue should have ever only affected android versions 4.1-4.4.  5.0 and above enable 1.2 by default and 4.0 and below don't support 1.1 or 1.2 at all.
