### ISSUE TITLE
Not Working on IOS 9 with acceptAllCerts = true

### ISSUE THREAD

**Issue by vizeke** [wymsee/cordova-HTTP#62]
I have a webApi with a non valid certificate, so i just set acceptAllCerts to true to ignore the certificate validation.

Testing it works on IOS 8.4 but fail on 9.0.

**Comment by jmallien** [comment]
I think this is due to the change in iOS that now all http-requests are affected by the application transport security (ATS).

You'll have to set an exception (in that plist thing) for your domain (or everything) that allows invalid certificates.

https://forums.developer.apple.com/thread/3544
