### ISSUE TITLE
Question: Compatibility with Embedded Youtube Player

### ISSUE THREAD

**Issue by jason-engage** [wymsee/cordova-HTTP#63]
I'm using the embedded YT player on a cordova app. It works fine on iOS, but there are videos that work on iOS that don't work on Android. On android, I get the 'playback is restricted on certain sites' message instead of the video. I read that this might have something to do with the http referrer being sent to youtube with the get request of each video. Is there a way for your plugin to modify those requests? I'm also using xwalk, but the issue is there whether or not I have xwalk included.

Thanks

**Comment by shawns582** [comment]
Did this plugin help you to embed the videos properly? I have the same issue and am looking for a fix.  Thanks!

**Comment by rastermax** [comment]
looking to solve the same issue, so far no luck.
tried to filter the youtube videos, but the embeddale flags and licensedContent ones of a youtube video don't give a good indications wether a video can be played in a cordova app.

**Comment by jason-engage** [comment]
@shawns582 I never got it to work right. Please let us know if you figure out how tho!

**Comment by rastermax** [comment]
it might be a http referer problem since i'm in a cordova app. currently investigating that.

**Comment by shawns582** [comment]
It is an http referer problem.

I had to do a workaround where I embed the video on my server and use an
iframe to embed that server page with the video into my app. I then used a
cross-domain messaging plugin like postmessage to enable two way
communication between my app and the video on the server. It works but it
is a little hoky.

If you don't need to access local files you can also have all of the app
files besides config.xml reside on the server.

I hope this helps...I struggled with this for a bit..so hopefully it helps
others.

If anyone has a cleaner way to address the http referer issue I'd love to
know it.

**Comment by rastermax** [comment]
Shawns582, thanks for info.
Good idea.
Will continue to monitor any cleaner way to do. For now I switched to another source of media for my app but  I still plan to support ytube in the future.
