### ISSUE TITLE
Double URL encoding gotcha on Android

### ISSUE THREAD

**Issue by possan** [wymsee/cordova-HTTP#69]
Just a heads up, found this issue out on Android after a few hours of debugging...

Issuing a GET call with a query string (not passed as an object) will double urlencode the already urlencoded url argument:

```
cordovaHTTP.get('http://test/?parameter=some+escaped+string', {}, {}, function() { ... });
```

will hit [this line in the plugin](https://github.com/wymsee/cordova-HTTP/blob/master/src/android/com/synconset/CordovaHTTP/CordovaHttpGet.java#L36) which in turn will call [this code in http request library](https://github.com/kevinsawicki/http-request/blob/master/lib/src/main/java/com/github/kevinsawicki/http/HttpRequest.java#L1011) - which will re-encode the url.

Expected outcome - don't re encode input url.

**Comment by TheKiteEatingTree** [comment]
Fixed with PR #8
