### ISSUE TITLE
Doesn't work with cordova iOS v3.9.n

### ISSUE THREAD

**Issue by MayurChandra** [wymsee/cordova-HTTP#73]
Tested with Cordova iOS3.9.2 and the app crashes.

Works fine with cordova iOS3.8.0

CoreFoundation Framework?

**Comment by Jacse** [comment]
I'm not able to install the plugin on the newest android version either:
`Failed to install 'com.synconset.cordovaHTTP':Error: Expected plugin to have ID "cordova-plugin-file" but got "org.apache.cordova.file".`

**Comment by dekelev** [comment]
I'm getting the same error when installing the plugin with Android platform and Cordova engine v5.4.0

**Comment by MayurChandra** [comment]
Tried it with cordova iOS@3.9.1 and get the following crash in CordovaHttpPlugin.m file

<img width="717" alt="screen shot 2016-02-03 at 10 44 05" src="https://cloud.githubusercontent.com/assets/2393504/12780008/70d2bd58-ca63-11e5-99c0-3aff83bd7488.png">

**Comment by TheKiteEatingTree** [comment]
Please try with latest version
