### ISSUE TITLE
Unable to register this plugin -- what am I missing?

### ISSUE THREAD

**Issue by jprashant28** [wymsee/cordova-HTTP#78]
Hello

I am excited about this plugin, but have not been able to get it to work.

I started a new cordova application.  Then using CLI I installed this plugin as such:
cordova plugin add cordova-plugin-http

I see that the plug in is installed.  Since my application uses Angular, I also had the whitelist plugin automatically available and access origin set to *.

I do : var ngapp = angular.module('myApp', ['cordovaHTTP']);  as the example provides.

Then in my controller, I am trying to access cordovaHTTP and I am unable to.

So finally I placed a try catch in cordovaHTTP.js file and I see that I am getting the following error.

On this line -> var exec = require('cordova/exec');
I am getting that "require is not defined".

I have been at it for over 2 weeks.  Any guidance will help.

**Comment by jprashant28** [comment]
I am closing this item.... the issue was multiple things I was doing wrong.
1. The Plugin was not registered correctly --- FIXED it
2. Using Angular made the usage of the plugin tricky -- modified cordovaHTTP.js to remove the angular components ... and used it directly with window.cordovaHTTP and it works very well..

**Comment by keerthivasan-r** [comment]
@jprashant28  Sorry for commenting on a closed issue. I'm getting into same problem. How to register the plugin correctly? I mean the ordering of js scripts in index.html. I would also love to use it as angular service. were you able to achieve it? For me, it throws either require variable is not defined or cordovaHTTP module is not defined

**Comment by jprashant28** [comment]
I ended up not using http Cordova.
